**Copyright: © NexStream Technical Education, LLC**.  
All rights reserved

#**Setup**  

Follow the instructions below and execute your code
with the provided doctest module.
Be sure to name the variables as shown and adhere to
the APIs in the functions so that your module passes the doctests

**NOTE - for the vector and matrix operations, you must
perform the operations using standard Python functions unless specified below.
In other words, no imported libraries such as numpy may be used in this part of the assignment, use Python 1-D and 2-D arrays/lists.**

In [5]:
#Vector and Matrix Variable initializations

#(1)  Create a vector called Va with the following components
#     2  5  7
#YOUR CODE HERE

Va = [2, 5, 7]

#(2)  Create a vector called Vb with the following components
#     5  2.3  9
#YOUR CODE HERE


Vb = [5, 2.3, 9]


#(3)  Create a 3x3 matrix called Ma with the following values
#     3    2   9.1
#     7   10   14
#     3  0.5   17.2
#YOUR CODE HERE


Ma = [[3, 2, 9.1],
      [7, 10, 14],
      [3, 0.5, 17.2]]




#(4)  Create a 3x3 matrix called Mb with the following values
#     8    17.3  7.8
#     2.9   1    1.4
#     5    0.5   1.2
#YOUR CODE HERE


Mb = [[8, 17.3, 7.8],
      [2.9, 1, 1.4],
      [5, 0.5, 1.2]]



#(5)  Create a 3x2 matrix called Mc with the following values
#     3    2
#     7   10
#     3  0.5
#YOUR CODE HERE


Mc = [[3, 2],
      [7, 10],
      [3, 0.5]]



#**Part A:  Vector operations**  

Follow the instructions below and execute your code
with the provided doctest module.
Be sure to name the variables as shown and adhere to
the APIs in the functions so that your module passes the doctests

**NOTE - for the vector and matrix operations, you must
perform the operations using standard Python functions unless specified below.
In other words, no imported libraries such as numpy may be used in this assignment, use Python 1-D and 2-D arrays/lists.**

In [6]:
#-----------   Part A   -----------
# Create the following functions which perform the operations as described
# Be sure to follow the exact function API as you will test with the doctest module below

###########################################################
####            Vector operations                      ####
#### All A, B function parameter inputs are vectors.   ####

#(1)   def vecScale(A, a):
#         return vector A scaled by scalar a
#
#YOUR CODE HERE

def vecScale(A, a):
    """
    Return the vector A scaled by scalar a.
    """
    return [a * i for i in A]



#(2)   def vecAdd(A, B):
#         return the sum of vectors A and B
#
#YOUR CODE HERE


def vecAdd(A, B):
    """
    Return the sum of vectors A and B.
    """
    return [A[i] + B[i] for i in range(len(A))]



#(3)   def vecSub(A, B):
#         return the difference of vectors A and B
#
#YOUR CODE HERE

def vecSub(A, B):
    """
    Return the difference of vectors A and B.
    """
    return [A[i] - B[i] for i in range(len(A))]



#(4)   def vecDot(A, B):
#         return the dot product of vectors A and B
#
#YOUR CODE HERE

def vecDot(A, B):
    """
    Return the dot product of vectors A and B.
    """
    return sum(A[i] * B[i] for i in range(len(A)))

#(5)  def vecLinOp1(A, B, a):
#         return the product of B scaled by 'a' and A
#
#YOUR CODE HERE

def vecLinOp1(A, B, a):
    """
    Return the product of vector B scaled by 'a' and vector A.
    """
    return vecDot(vecScale(B, a), A)



#(6)  def vecLinOp2(A, B):
#         return the difference of B and A then multiplied by B
#
#YOUR CODE HERE

def vecLinOp2(A, B):
    """
    Return the difference of vector B and A then multiplied by vector B.
    """
    return vecDot(vecSub(B, A), B)



#-------------------------------------------------------------------------------------------------
#Test with the following doctest test vectors.
#DO NOT EDIT THE TEST CODE!!!!
#Even changing the spacing can cause errors.
#The test code will automatically execute when you run the cell.
#You should test all your combination of outputs but your code at least must pass these exact tests.
#If your code fails, you will see a description in the console cell.
#If your code passes, you will see the message: "TestResults(failed=0, attempted=N)", where N is the number of tests
import doctest
"""
 >>> vecScale(Va, 7)
 [14, 35, 49]
 >>> vecAdd(Va, Vb)
 [7, 7.3, 16]
 >>> vecSub(Vb, Va)
 [3, -2.7, 2]
 >>> vecDot(Va, Vb)
 84.5
 >>> vecLinOp1(Va, Vb, 3.2)
 270.4
 >>> vecLinOp2(Va, Vb)
 26.79
"""
doctest.testmod()


TestResults(failed=0, attempted=6)

#**Part B:  Matrix operations**  

Follow the instructions below and execute your code
with the provided doctest module.
Be sure to name the variables as shown and adhere to
the APIs in the functions so that your module passes the doctests

**NOTE - for the vector and matrix operations, you must
perform the operations using standard Python functions unless specified below.
In other words, no imported libraries such as numpy may be used in this assignment, use Python 1-D and 2-D arrays/lists.**

In [7]:
#-----------   Part B   -----------
# Create the following functions which perform the operations as described
# Be sure to follow the exact function API as you will test with the doctest module below

###########################################################
####            Matrix operations                      ####
#### All A, B function parameter inputs are matrices.  ####
#
#(1)  def matScale(A, a):
#         return the A scaled by a
#
#YOUR CODE HERE

def matScale(A, a):
    """
    Return the matrix A scaled by a.
    """
    return [[a * A[i][j] for j in range(len(A[0]))] for i in range(len(A))]

#(2)  def matAdd(A, B):
#         return the sum of matrix A and B
#
#YOUR CODE HERE

def matAdd(A, B):
    """
    Return the sum of matrix A and B.
    """
    return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]


#(3)  def matSub(A, B):
#         return the difference of matrix A and B
#
#YOUR CODE HERE


def matSub(A, B):
    """
    Return the difference of matrix A and B.
    """
    return [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]


#(4  def matMult(A, B):
#         return the product of matrix A and B
#
#YOUR CODE HERE

def matMult(A, B):
    """
    Return the product of matrix A and B.
    """
    result = [[0 for j in range(len(B[0]))] for i in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

#(5)  def matTrans(A):
#         return the transpose of matrix A
#
#YOUR CODE HERE

def matTrans(A):
    """
    Return the transpose of matrix A.
    """
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]


#(6)  def matlinOp1(A,B):
#         A,B are matrices
#         return the transpose of the product of A and B
#
#YOUR CODE HERE


def matLinOp1(A, B):
    """
    Return the transpose of the product of A and B.
    """
    return matTrans(matMult(A, B))


#(7)  def matLinOp2(A,B):
#         A,B are matrices
#         return the sum of -B and -A
#
#YOUR CODE HERE

def matLinOp2(A, B):
    """
    Return the sum of -B and -A.
    """
    return matAdd(matScale(A, -1), matScale(B, -1))


#(8)  def matLinOp3(A,B,a):
#         A,B are matrices, a is a scalar
#         return the product of A scaled by 'a' and B
#
#YOUR CODE HERE

def matLinOp3(A, B, a):
    """
    Return the product of A scaled by 'a' and B.
    """
    return matMult(matScale(A, a), B)

#(9)  def matLinOp4(A,B,C):
#         A,B,C are matrices
#         return the product of the transpose of C and the sum of A and B
#YOUR CODE HERE

def matLinOp4(A, B, C):
    """
    Return the product of the transpose of C and the sum of A and B.
    """
    return matMult(matTrans(C), matAdd(A, B))



#-------------------------------------------------------------------------------------------------
#Test with the following doctest test vectors.
#DO NOT EDIT THE TEST CODE!!!!
#Even changing the spacing can cause errors.
#The test code will automatically execute when you run the cell.
#You should test all your combination of outputs but your code at least must pass these exact tests.
#If your code fails, you will see a description in the console cell.
#If your code passes, you will see the message: "TestResults(failed=0, attempted=N)", where N is the number of tests
import doctest
"""
 >>> matScale(Ma, 4.8)
 [[14.399999999999999, 9.6, 43.68], [33.6, 48.0, 67.2], [14.399999999999999, 2.4, 82.55999999999999]]
 >>> matAdd(Ma, Mb)
 [[11, 19.3, 16.9], [9.9, 11, 15.4], [8, 1.0, 18.4]]
 >>> matSub(Ma, Mb)
 [[-5, -15.3, 1.2999999999999998], [4.1, 9, 12.6], [-2, 0.0, 16.0]]
 >>> matMult(Ma, Mc)
 [[50.3, 30.55], [133, 121.0], [64.1, 19.6]]
 >>> matTrans(Mc)
 [[3, 7, 3], [2, 10, 0.5]]
 >>> matLinOp1(Ma, Mb)
 [[75.3, 155.0, 111.45], [58.45, 138.10000000000002, 61.00000000000001], [37.12, 85.39999999999999, 44.739999999999995]]
 >>> matLinOp2(Ma, Mb)
 [[-11, -19.3, -16.9], [-9.9, -11, -15.4], [-8, -1.0, -18.4]]
 >>> matLinOp3(Ma, Mb, 3.7)
 [[278.61, 216.26500000000004, 137.34400000000002], [573.5, 510.97, 315.98], [412.365, 225.70000000000002, 165.538]]
 >>> matLinOp4(Ma, Mb, Mc)
 [[126.3, 137.9, 213.7], [125.0, 149.1, 197.0]]

"""
doctest.testmod()

TestResults(failed=0, attempted=9)

#**Part C:  Special Vector and Matrix operations**

Follow the instructions below and execute your code
with the provided doctest module.
Be sure to name the variables as shown and adhere to
the APIs in the functions so that your module passes the doctests

**NOTE - you may use numpy functions only to perform the operations in this section (no other machine learning library functions).**

In [8]:
#-----------   Part C   -----------
# Create the following functions which perform the operations as described
# Be sure to follow the exact function API as you will test with the doctest module below

import numpy as np

#(1)  def diag_inverse(A):
#         return the inverse of A (A will be a diagonal matrix)
#Do NOT use an inverse calculator function
#YOUR CODE HERE

def diag_inverse(A):
    """
    Return the inverse of a diagonal matrix A.
    """
    diag = np.diag(A)
    inv_diag = 1.0 / diag
    return np.diag(inv_diag)

#(2)  def ortho_inverse(A):
#         return a boolean == true if A is orthonormal
#You MAY use the numpy linalg.inv function
#YOUR CODE HERE

def ortho_inverse(A):
    """
    Return True if the matrix A is orthonormal.
    """
    return np.allclose(A, np.linalg.inv(A).T)


# Calculate the mean of the columns in a matrix
#(3)  def data_mean(data_in):
#         return a vector containing the mean of each column
#YOUR CODE HERE

def data_mean(data_in):
    """
    Return a vector containing the mean of each column in data_in.
    """

    return np.mean(data_in, axis=0)


# Shift data to origin by subtracting column means from columns
#(4)  def data_center(data_in, data_mean):
#       return a matrix comprised of data_in with data_mean subtracted
#YOUR CODE HERE

def data_center(data_in, data_mean):
    """
    Return a matrix comprised of data_in with data_mean subtracted.
    """

    return data_in - data_mean


#(5)  def data_cov(A):
#         return the covariance of matrix A
#You may NOT use a covariance calculator function
#You MAY use the numpy matmul function
#YOUR CODE HERE



def data_cov(A):
    '''
    This function computes the covariance matrix of a given dataset.
    '''
    n = A.shape[0]
    centered_data = A - np.mean(A, axis=0)
    return np.matmul(centered_data.T, centered_data) / (n - 1)


#Run the doctest module.  DO NOT modify any code below this line!
import doctest
data_b = np.array([[43, 26, 28, 29, 42, 39],
                   [8.5, 5.0, 6.1, 4.6, 7.2, 7.4],
                   [170, 104, 121, 130, 159, 132],
                   [5.0, 5.9, 5.5, 5.8, 4.7, 5.7]])

mean_b = data_mean(data_b)
print('mean_b:', mean_b)



center_b = data_center(data_b, mean_b)
print('center_b:', center_b)
covariance_b = data_cov(center_b)
print('covariance_b:', covariance_b)

"""
  >>> print(diag_inverse(np.array([[2,    0 ,   0], [0, -0.25,   0], [0,    0,   10]])))
  [[ 0.5  0.   0. ]
   [ 0.  -4.   0. ]
   [ 0.   0.   0.1]]
  >>> print(ortho_inverse(np.array([[1,     0 ,   0], [0,    -1 ,   0], [0,     0 ,   1]])))
  True
  >>> print(ortho_inverse(np.array([[1,     0 ,   1], [0,      1 ,   0], [1,      1 ,   0]])))
  False
  >>> print(np.round(mean_b, 4))
  [56.625 35.225 40.15  42.35  53.225 46.025]
  >>> print(np.round(center_b, 4))
  [[-13.625  -9.225 -12.15  -13.35  -11.225  -7.025]
   [-48.125 -30.225 -34.05  -37.75  -46.025 -38.625]
   [113.375  68.775  80.85   87.65  105.775  85.975]
   [-51.625 -29.325 -34.65  -36.55  -48.525 -40.325]]
  >>> print(np.round(covariance_b, 4))
  [[6006.8958 3630.5125 4253.125  4607.6083 5621.7458 4594.5792]
   [3630.5125 2196.2025 2572.605  2788.035  3397.4425 2775.9025]
   [4253.125  2572.605  3014.79   3266.85   3978.945  3249.625 ]
   [4607.6083 2788.035  3266.85   3540.57   4310.6883 3520.4883]
   [5621.7458 3397.4425 3978.945  4310.6883 5262.4425 4302.4492]
   [4594.5792 2775.9025 3249.625  3520.4883 4302.4492 3519.6825]]
"""

doctest.testmod()


mean_b: [56.625 35.225 40.15  42.35  53.225 46.025]
center_b: [[-13.625  -9.225 -12.15  -13.35  -11.225  -7.025]
 [-48.125 -30.225 -34.05  -37.75  -46.025 -38.625]
 [113.375  68.775  80.85   87.65  105.775  85.975]
 [-51.625 -29.325 -34.65  -36.55  -48.525 -40.325]]
covariance_b: [[6006.89583333 3630.5125     4253.125      4607.60833333 5621.74583333
  4594.57916667]
 [3630.5125     2196.2025     2572.605      2788.035      3397.4425
  2775.9025    ]
 [4253.125      2572.605      3014.79       3266.85       3978.945
  3249.625     ]
 [4607.60833333 2788.035      3266.85       3540.57       4310.68833333
  3520.48833333]
 [5621.74583333 3397.4425     3978.945      4310.68833333 5262.4425
  4302.44916667]
 [4594.57916667 2775.9025     3249.625      3520.48833333 4302.44916667
  3519.6825    ]]


TestResults(failed=0, attempted=6)