**Copyright: © NexStream Technical Education, LLC**.  
All rights reserved 

#**Setup**  

Follow the instructions below and execute your code
with the provided doctest module.
Be sure to name the variables as shown and adhere to
the APIs in the functions so that your module passes the doctests

**NOTE - for the vector and matrix operations, you must 
perform the operations using standard Python functions unless specified below.
In other words, no imported libraries such as numpy may be used in this part of the assignment, use Python 1-D and 2-D arrays/lists.**

In [ ]:
#Vector and Matrix Variable initializations

#(1)  Create a vector called Va with the following components
#     2  5  7
#YOUR CODE HERE

#(2)  Create a vector called Vb with the following components
#     5  2.3  9
#YOUR CODE HERE

#(3)  Create a 3x3 matrix called Ma with the following values
#     3    2   9.1
#     7   10   14
#     3  0.5   17.2
#YOUR CODE HERE

#(4)  Create a 3x3 matrix called Mb with the following values
#     8    17.3  7.8
#     2.9   1    1.4
#     5    0.5   1.2
#YOUR CODE HERE

#(5)  Create a 3x2 matrix called Mc with the following values
#     3    2  
#     7   10 
#     3  0.5
#YOUR CODE HERE



#**Part A:  Vector operations**  

Follow the instructions below and execute your code
with the provided doctest module.
Be sure to name the variables as shown and adhere to
the APIs in the functions so that your module passes the doctests

**NOTE - for the vector and matrix operations, you must 
perform the operations using standard Python functions unless specified below.
In other words, no imported libraries such as numpy may be used in this assignment, use Python 1-D and 2-D arrays/lists.**

In [ ]:
#-----------   Part A   -----------
# Create the following functions which perform the operations as described
# Be sure to follow the exact function API as you will test with the doctest module below

###########################################################
####            Vector operations                      ####
#### All A, B function parameter inputs are vectors.   ####

#(1)   def vecScale(A, a):
#         return vector A scaled by scalar a
#
#YOUR CODE HERE

#(2)   def vecAdd(A, B):
#         return the sum of vectors A and B 
# 
#YOUR CODE HERE

#(3)   def vecSub(A, B):
#         return the difference of vectors A and B 
# 
#YOUR CODE HERE

#(4)   def vecDot(A, B):
#         return the dot product of vectors A and B 
#
#YOUR CODE HERE

#(5)  def vecLinOp1(A, B, a):
#         return the product of B scaled by 'a' and A 
#
#YOUR CODE HERE

#(6)  def vecLinOp2(A, B):
#         return the difference of B and A then multiplied by B
#
#YOUR CODE HERE






#-------------------------------------------------------------------------------------------------
#Test with the following doctest test vectors.
#DO NOT EDIT THE TEST CODE!!!!
#Even changing the spacing can cause errors.
#The test code will automatically execute when you run the cell.
#You should test all your combination of outputs but your code at least must pass these exact tests.
#If your code fails, you will see a description in the console cell.
#If your code passes, you will see the message: "TestResults(failed=0, attempted=N)", where N is the number of tests
import doctest
"""
 >>> vecScale(Va, 7)
 [14, 35, 49]
 >>> vecAdd(Va, Vb)
 [7, 7.3, 16]
 >>> vecSub(Vb, Va)
 [3, -2.7, 2]
 >>> vecDot(Va, Vb)
 84.5
 >>> vecLinOp1(Va, Vb, 3.2)
 270.4
 >>> vecLinOp2(Va, Vb)
 26.79
"""
doctest.testmod()


#**Part B:  Matrix operations**  

Follow the instructions below and execute your code
with the provided doctest module.
Be sure to name the variables as shown and adhere to
the APIs in the functions so that your module passes the doctests

**NOTE - for the vector and matrix operations, you must 
perform the operations using standard Python functions unless specified below.
In other words, no imported libraries such as numpy may be used in this assignment, use Python 1-D and 2-D arrays/lists.**

In [ ]:
#-----------   Part B   -----------
# Create the following functions which perform the operations as described
# Be sure to follow the exact function API as you will test with the doctest module below

###########################################################
####            Matrix operations                      ####
#### All A, B function parameter inputs are matrices.  ####
#
#(1)  def matScale(A, a):
#         return the A scaled by a
#
#YOUR CODE HERE


#(2)  def matAdd(A, B):
#         return the sum of matrix A and B 
#
#YOUR CODE HERE


#(3)  def matSub(A, B):
#         return the difference of matrix A and B 
#
#YOUR CODE HERE


#(4  def matMult(A, B):
#         return the product of matrix A and B 
#
#YOUR CODE HERE


#(5)  def matTrans(A):
#         return the transpose of matrix A
#
#YOUR CODE HERE


#(6)  def matlinOp1(A,B):
#         A,B are matrices
#         return the transpose of the product of A and B
#
#YOUR CODE HERE


#(7)  def matLinOp2(A,B):
#         A,B are matrices
#         return the sum of -B and -A 
#
#YOUR CODE HERE


#(8)  def matLinOp3(A,B,a):
#         A,B are matrices, a is a scalar
#         return the product of A scaled by 'a' and B 
#
#YOUR CODE HERE


#(9)  def matLinOp4(A,B,C):
#         A,B,C are matrices
#         return the product of the transpose of C and the sum of A and B
#YOUR CODE HERE




#-------------------------------------------------------------------------------------------------
#Test with the following doctest test vectors.
#DO NOT EDIT THE TEST CODE!!!!
#Even changing the spacing can cause errors.
#The test code will automatically execute when you run the cell.
#You should test all your combination of outputs but your code at least must pass these exact tests.
#If your code fails, you will see a description in the console cell.
#If your code passes, you will see the message: "TestResults(failed=0, attempted=N)", where N is the number of tests
import doctest
"""
 >>> matScale(Ma, 4.8)
 [[14.399999999999999, 9.6, 43.68], [33.6, 48.0, 67.2], [14.399999999999999, 2.4, 82.55999999999999]]
 >>> matAdd(Ma, Mb)
 [[11, 19.3, 16.9], [9.9, 11, 15.4], [8, 1.0, 18.4]]
 >>> matSub(Ma, Mb)
 [[-5, -15.3, 1.2999999999999998], [4.1, 9, 12.6], [-2, 0.0, 16.0]]
 >>> matMult(Ma, Mc)
 [[50.3, 30.55], [133, 121.0], [64.1, 19.6]]
 >>> matTrans(Mc)
 [[3, 7, 3], [2, 10, 0.5]]
 >>> matLinOp1(Ma, Mb)
 [[75.3, 155.0, 111.45], [58.45, 138.10000000000002, 61.00000000000001], [37.12, 85.39999999999999, 44.739999999999995]]
 >>> matLinOp2(Ma, Mb)
 [[-11, -19.3, -16.9], [-9.9, -11, -15.4], [-8, -1.0, -18.4]]
 >>> matLinOp3(Ma, Mb, 3.7)
 [[278.61, 216.26500000000004, 137.34400000000002], [573.5, 510.97, 315.98], [412.365, 225.70000000000002, 165.538]]
 >>> matLinOp4(Ma, Mb, Mc)
 [[126.3, 137.9, 213.7], [125.0, 149.1, 197.0]]

"""
doctest.testmod()

#**Part C:  Special Vector and Matrix operations**

Follow the instructions below and execute your code
with the provided doctest module.
Be sure to name the variables as shown and adhere to
the APIs in the functions so that your module passes the doctests

**NOTE - you may use numpy functions only to perform the operations in this section (no other machine learning library functions).** 

In [ ]:
#-----------   Part C   -----------
# Create the following functions which perform the operations as described
# Be sure to follow the exact function API as you will test with the doctest module below

import numpy as np

#(1)  def diag_inverse(A):
#         return the inverse of A (A will be a diagonal matrix)
#Do NOT use an inverse calculator function
#YOUR CODE HERE


#(2)  def ortho_inverse(A):
#         return a boolean == true if A is orthonormal
#You MAY use the numpy linalg.inv function
#YOUR CODE HERE


# Calculate the mean of the columns in a matrix
#(3)  def data_mean(data_in):
#         return a vector containing the mean of each column
#YOUR CODE HERE


# Shift data to origin by subtracting column means from columns
#(4)  def data_center(data_in, data_mean):
#       return a matrix comprised of data_in with data_mean subtracted 
#YOUR CODE HERE


#(5)  def data_cov(A):
#         return the covariance of matrix A
#You may NOT use a covariance calculator function
#You MAY use the numpy matmul function
#YOUR CODE HERE


#Run the doctest module.  DO NOT modify any code below this line!
import doctest
data_b = np.array([[43, 26, 28, 29, 42, 39],
                   [8.5, 5.0, 6.1, 4.6, 7.2, 7.4],
                   [170, 104, 121, 130, 159, 132],
                   [5.0, 5.9, 5.5, 5.8, 4.7, 5.7]])

mean_b = data_mean(data_b)
print('mean_b:', mean_b)
center_b = data_center(data_b, mean_b)
print('center_b:', center_b)
covariance_b = data_cov(center_b)
print('covariance_b:', covariance_b)

"""
  >>> print(diag_inverse(np.array([[2,    0 ,   0], [0, -0.25,   0], [0,    0,   10]])))
  [[ 0.5  0.   0. ]
   [ 0.  -4.   0. ]
   [ 0.   0.   0.1]]
  >>> print(ortho_inverse(np.array([[1,     0 ,   0], [0,    -1 ,   0], [0,     0 ,   1]])))
  True
  >>> print(ortho_inverse(np.array([[1,     0 ,   1], [0,      1 ,   0], [1,      1 ,   0]])))
  False
  >>> print(np.round(mean_b, 4))
  [ 34.5      6.4667 136.       5.4333]
  >>> print(np.round(center_b, 4))
  [[  8.5      2.0333  34.      -0.4333]
   [ -8.5     -1.4667 -32.       0.4667]
   [ -6.5     -0.3667 -15.       0.0667]
   [ -5.5     -1.8667  -6.       0.3667]
   [  7.5      0.7333  23.      -0.7333]
   [  4.5      0.9333  -4.       0.2667]]
  >>> print(np.round(covariance_b, 4))
  [[ 5.8700e+01  1.0420e+01  1.6920e+02 -2.8800e+00]
   [ 1.0420e+01  2.2627e+00  2.9180e+01 -5.1270e-01]
   [ 1.6920e+02  2.9180e+01  5.9720e+02 -1.0160e+01]
   [-2.8800e+00 -5.1270e-01 -1.0160e+01  2.3070e-01]]
"""

doctest.testmod(verbose=True)


mean_b: [ 34.5          6.46666667 136.           5.43333333]
center_b: [[  8.5          2.03333333  34.          -0.43333333]
 [ -8.5         -1.46666667 -32.           0.46666667]
 [ -6.5         -0.36666667 -15.           0.06666667]
 [ -5.5         -1.86666667  -6.           0.36666667]
 [  7.5          0.73333333  23.          -0.73333333]
 [  4.5          0.93333333  -4.           0.26666667]]
covariance_b: [[ 5.87000000e+01  1.04200000e+01  1.69200000e+02 -2.88000000e+00]
 [ 1.04200000e+01  2.26266667e+00  2.91800000e+01 -5.12666667e-01]
 [ 1.69200000e+02  2.91800000e+01  5.97200000e+02 -1.01600000e+01]
 [-2.88000000e+00 -5.12666667e-01 -1.01600000e+01  2.30666667e-01]]
Trying:
    print(diag_inverse(np.array([[2,    0 ,   0], [0, -0.25,   0], [0,    0,   10]])))
Expecting:
    [[ 0.5  0.   0. ]
     [ 0.  -4.   0. ]
     [ 0.   0.   0.1]]
ok
Trying:
    print(ortho_inverse(np.array([[1,     0 ,   0], [0,    -1 ,   0], [0,     0 ,   1]])))
Expecting:
    True
ok
Trying:
    prin

TestResults(failed=0, attempted=6)